### ISSUE TITLE
user is undefined

### ISSUE THREAD

**Issue by hutchic** [mglaman/ansible-role-atom#1]
https://github.com/mglaman/ansible-role-atom/blob/master/tasks/main.yml#L14 

```
TASK [mglaman.atom : Ensure user Atom directory] 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'kit_ui_user' is undefined"}    
```

**Comment by mglaman** [comment]
Yeah, sorry. I started to abstract this and didn't realize that. I'll get a fix up

**Comment by mglaman** [comment]
There's other bugs, but this one was fixed. Working on the others :)
